### ISSUE TITLE
Кнопки бонусов

### ISSUE THREAD

**Issue by Ku3mi41** [VDenisyuk/ovh-angular#1]
Кнопки бонусов нажимаются даже в состоянии disabled, и можно накрутить 26% бонуса в любом заводе\товаре.

**Comment by VDenisyuk** [comment]
Да, это осознано. Я даю возможность задать бонус произвольно, на усмотрение пользователя. В игре достаточно много источников получения бонусов (инновации, корпы, региональные бонусы) и учесть все возможные комбинации сложно.

**Comment by Ku3mi41** [comment]
Тогда на кнопках не должно быть disabled, т.к. это из-за этого показывается курсор not-allowed, и складывается впечатление что нажиматься они не должны.

**Comment by VDenisyuk** [comment]
Речь о каком-то конкретном юните? Я еще не успел пройтись по всем, но во всех вновь добавленных я убирал disabled у fieldset-тега и удалял блок кнопок вообще. В следующей версии я планирую оставить только один темплейт юнита (по одному на каждый тип), а данные подгружать в json-формате. И перейти на Vue :) Нет предела совершенству!

**Comment by Ku3mi41** [comment]
`$(this).closest('form').find('#10Q').toggleClass('disabled')`
`$(this).closest('form').find('#15Q').toggleClass('disabled')`

на кнопках висят такие события. 10/15% отключают друг друга.

**Comment by VDenisyuk** [comment]
Me too
